package me.stringdotjar.reflectaot.codegen

import org.objectweb.asm.ClassWriter
import org.objectweb.asm.Opcodes
import org.objectweb.asm.Type
import org.objectweb.asm.commons.GeneratorAdapter
import org.objectweb.asm.commons.Method
import java.io.File
import org.objectweb.asm.commons.Method as AsmMethod

/**
 * Emits per-type accessor classes under `me.stringdotjar.reflectaot.generated.access` with static methods that mirror
 * [ReflectApiNames] entry points for a single concrete receiver type.
 */
object AccessBytecodeEmitter {

  private val OBJECT_TYPE = Type.getType(Any::class.java)
  private val STRING_TYPE = Type.getType(String::class.java)
  private val STRING_ARRAY_TYPE = Type.getType("[Ljava/lang/String;")
  private val LIST_TYPE = Type.getType(List::class.java)
  private val BICONSUMER_TYPE = Type.getType(java.util.function.BiConsumer::class.java)
  private val METHOD_ID_TYPE = Type.getType("Lme/stringdotjar/reflectaot/ReflectMethodId;")
  private val M_REFLECT_METHOD_ID_INIT = AsmMethod("<init>", Type.VOID_TYPE, arrayOf(Type.INT_TYPE))
  private val M_BICONS_ACCEPT = AsmMethod("accept", Type.VOID_TYPE, arrayOf(OBJECT_TYPE, OBJECT_TYPE))

  /**
   * Returns the stable internal name for the accessor class that specializes calls for [typeInternal].
   *
   * @param typeInternal JVM internal name of the user type such as `com/example/Foo`.
   * @return Internal name of the generated accessor class under the generated access package.
   */
  fun accessInternalName(typeInternal: String): String =
    "me/stringdotjar/reflectaot/generated/access/" + typeInternal.replace('/', '_') + "ReflectAOT"

  /**
   * Writes one accessor class file containing field and property helpers, `fields`, `copy`, and a `callMethod` switch
   * for ids bound to this receiver type.
   *
   * @param type Introspected receiver metadata used to choose fields, properties, and methods.
   * @param outputDir Root directory that will receive generated bytecode.
   * @param roots Classpath roots forwarded to helpers that need subtype checks.
   * @param methodBindings Full binding list filtered internally to ids relevant for this type.
   */
  fun emit(type: TypeIntrospection.IntrospectedType, outputDir: File, roots: Collection<File>, methodBindings: List<MethodIdBinding>) {
    val ownerType = Type.getObjectType(type.internalName)
    val accessInternal = accessInternalName(type.internalName)
    val cw = ClassWriter(ClassWriter.COMPUTE_FRAMES)
    cw.visit(
      Opcodes.V1_7,
      Opcodes.ACC_PUBLIC + Opcodes.ACC_FINAL + Opcodes.ACC_SUPER,
      accessInternal,
      null,
      "java/lang/Object",
      null,
    )
    run {
      val m = cw.visitMethod(Opcodes.ACC_PRIVATE, "<init>", "()V", null, null)
      m.visitCode()
      m.visitVarInsn(Opcodes.ALOAD, 0)
      m.visitMethodInsn(Opcodes.INVOKESPECIAL, "java/lang/Object", "<init>", "()V", false)
      m.visitInsn(Opcodes.RETURN)
      m.visitMaxs(0, 0)
      m.visitEnd()
    }

    emitField(type, cw, ownerType)
    emitSetField(type, cw, ownerType)
    emitHasField(type, cw)
    emitProperty(type, cw, ownerType)
    emitSetProperty(type, cw, ownerType)
    emitFields(type, cw, ownerType)
    emitForEachField(type, cw, ownerType)
    emitForEachProperty(type, cw, ownerType)
    emitCopy(type, cw, ownerType, roots)
    emitCallMethod(type, cw, ownerType, methodBindings, roots)
    emitForEachMethod(type, cw, methodBindings)

    cw.visitEnd()
    val out = File(outputDir, "$accessInternal.class")
    out.parentFile.mkdirs()
    out.writeBytes(cw.toByteArray())
  }

  private fun emitField(type: TypeIntrospection.IntrospectedType, cw: ClassWriter, ownerType: Type) {
    val m = AsmMethod(ReflectApiNames.FIELD, Type.getType(Any::class.java), arrayOf(ownerType, STRING_TYPE))
    val ga = verifyNonNull(m, cw)

    for ((name, desc) in type.fields) {
      stringEqualsThen(
        ga,
        name,
      ) {
        ga.loadArg(0)
        ga.getField(ownerType, name, Type.getType(desc))
        ga.box(Type.getType(desc))
        ga.returnValue()
      }
    }
    ga.throwException(Type.getType(IllegalArgumentException::class.java), "Unknown field")
    ga.endMethod()
  }

  private fun emitSetField(type: TypeIntrospection.IntrospectedType, cw: ClassWriter, ownerType: Type) {
    val m = AsmMethod(ReflectApiNames.SET_FIELD, Type.VOID_TYPE, arrayOf(ownerType, STRING_TYPE, OBJECT_TYPE))
    val ga = verifyNonNull(m, cw)

    for ((name, desc) in type.fieldsWritable) {
      val ft = Type.getType(desc)
      stringEqualsThen(
        ga,
        name,
      ) {
        ga.loadArg(0)
        ga.loadArg(2)
        ga.unbox(ft)
        ga.putField(ownerType, name, ft)
        ga.returnValue()
      }
    }
    ga.throwException(Type.getType(IllegalArgumentException::class.java), "Unknown field")
    ga.endMethod()
  }

  private fun emitHasField(type: TypeIntrospection.IntrospectedType, cw: ClassWriter) {
    val ownerType = Type.getObjectType(type.internalName)
    val m = AsmMethod(ReflectApiNames.HAS_FIELD, Type.BOOLEAN_TYPE, arrayOf(ownerType, STRING_TYPE))
    val ga = GeneratorAdapter(Opcodes.ACC_PUBLIC + Opcodes.ACC_STATIC, m, null, null, cw)
    ga.visitCode()
    ga.loadArg(1)
    val nonNull = ga.newLabel()
    ga.ifNonNull(nonNull)
    ga.push(false)
    ga.returnValue()
    ga.mark(nonNull)

    val allNames = LinkedHashSet<String>()
    type.instanceFieldsMeta.keys.forEach { allNames.add(it) }
    type.properties.forEach { allNames.add(it.name) }

    for (n in allNames) {
      stringEqualsThen(
        ga,
        n,
      ) {
        ga.push(true)
        ga.returnValue()
      }
    }
    ga.push(false)
    ga.returnValue()
    ga.endMethod()
  }

  private fun emitProperty(type: TypeIntrospection.IntrospectedType, cw: ClassWriter, ownerType: Type) {
    val m = AsmMethod(ReflectApiNames.PROPERTY, Type.getType(Any::class.java), arrayOf(ownerType, STRING_TYPE))
    val ga = verifyNonNull(m, cw)

    for (p in type.properties) {
      if (!ReflectPropertyAnalysis.beanReadable(p, type)) {
        continue
      }
      stringEqualsThen(
        ga,
        p.name,
      ) {
        if (p.getterName != null && p.getterDesc != null) {
          ga.loadArg(0)
          val rt = Type.getReturnType(p.getterDesc)
          ga.invokeVirtual(ownerType, AsmMethod(p.getterName, p.getterDesc))
          ga.box(rt)
        } else {
          val fn =
            p.fieldName
              ?: error("ReflectAOT internal: readable bean property ${p.name} has no getter but fieldName was null")
          ga.loadArg(0)
          val fd = type.fields.getValue(fn)
          ga.getField(ownerType, fn, Type.getType(fd))
          ga.box(Type.getType(fd))
        }
        ga.returnValue()
      }
    }
    for ((name, desc) in type.fields) {
      stringEqualsThen(
        ga,
        name,
      ) {
        ga.loadArg(0)
        ga.getField(ownerType, name, Type.getType(desc))
        ga.box(Type.getType(desc))
        ga.returnValue()
      }
    }
    ga.throwException(Type.getType(IllegalArgumentException::class.java), "Unknown property")
    ga.endMethod()
  }

  private fun emitSetProperty(type: TypeIntrospection.IntrospectedType, cw: ClassWriter, ownerType: Type) {
    val m = AsmMethod(ReflectApiNames.SET_PROPERTY, Type.VOID_TYPE, arrayOf(ownerType, STRING_TYPE, OBJECT_TYPE))
    val ga = verifyNonNull(m, cw)

    for (p in type.properties) {
      if (!ReflectPropertyAnalysis.beanWritableForEmit(p, type)) {
        continue
      }
      stringEqualsThen(
        ga,
        p.name,
      ) {
        if (p.setterName != null && p.setterDesc != null) {
          val args = Type.getArgumentTypes(p.setterDesc)
          if (args.size == 1) {
            ga.loadArg(0)
            ga.loadArg(2)
            ga.unbox(args[0])
            ga.invokeVirtual(ownerType, AsmMethod(p.setterName, p.setterDesc))
            ga.returnValue()
          }
        }
        if (p.fieldName != null && type.fieldsWritable.containsKey(p.fieldName)) {
          ga.loadArg(0)
          ga.loadArg(2)
          val ft = Type.getType(type.fieldsWritable.getValue(p.fieldName))
          ga.unbox(ft)
          ga.putField(ownerType, p.fieldName, ft)
          ga.returnValue()
        }
      }
    }
    for ((name, desc) in type.fieldsWritable) {
      stringEqualsThen(
        ga,
        name,
      ) {
        ga.loadArg(0)
        ga.loadArg(2)
        val ft = Type.getType(desc)
        ga.unbox(ft)
        ga.putField(ownerType, name, ft)
        ga.returnValue()
      }
    }
    ga.throwException(Type.getType(IllegalArgumentException::class.java), "Unknown property")
    ga.endMethod()
  }

  /** Switch on numeric id, unbox args from [java.util.List], then `invokevirtual` on the declaring type. */
  private fun emitCallMethod(type: TypeIntrospection.IntrospectedType, cw: ClassWriter, ownerType: Type, allBindings: List<MethodIdBinding>, roots: Collection<File>) {
    val bindings =
      allBindings
        .filter { JvmSubtype.isSubtype(type.internalName, it.userClassInternal, roots) }
        .sortedBy { it.id }
    val m = AsmMethod(ReflectApiNames.CALL_METHOD, Type.getType(Any::class.java), arrayOf(ownerType, Type.INT_TYPE, LIST_TYPE))
    val ga = GeneratorAdapter(Opcodes.ACC_PUBLIC + Opcodes.ACC_STATIC, m, null, null, cw)
    ga.visitCode()
    if (bindings.isEmpty()) {
      ga.throwException(
        Type.getType(IllegalArgumentException::class.java),
        "No Reflect.${ReflectApiNames.METHOD} bindings for ${type.internalName.replace('/', '.')}",
      )
      ga.endMethod()
      return
    }
    for (b in bindings) {
      val next = ga.newLabel()
      ga.loadArg(1)
      ga.push(b.id)
      ga.ifCmp(Type.INT_TYPE, GeneratorAdapter.NE, next)
      ga.loadArg(0)
      val argTypes = Type.getArgumentTypes(b.descriptor)
      for (i in argTypes.indices) {
        ga.loadArg(2)
        ga.push(i)
        ga.invokeInterface(LIST_TYPE, AsmMethod("get", OBJECT_TYPE, arrayOf(Type.INT_TYPE)))
        ga.unbox(argTypes[i])
      }
      val declaring = Type.getObjectType(b.declaringInternal)
      ga.invokeVirtual(declaring, AsmMethod(b.name, b.descriptor))
      val ret = Type.getReturnType(b.descriptor)
      if (ret == Type.VOID_TYPE) {
        ga.visitInsn(Opcodes.ACONST_NULL)
      } else {
        ga.box(ret)
      }
      ga.returnValue()
      ga.mark(next)
    }
    ga.throwException(
      Type.getType(IllegalArgumentException::class.java),
      "Unknown method id for ${type.internalName.replace('/', '.')}",
    )
    ga.endMethod()
  }

  /**
   * Shallow copy: `new` + public no-arg `<init>`, then `getfield`/`putfield` for each
   * [TypeIntrospection.instanceFieldsForCopy] entry (public, non-final).
   */
  private fun emitCopy(type: TypeIntrospection.IntrospectedType, cw: ClassWriter, ownerType: Type, roots: Collection<File>) {
    val refs = TypeIntrospection.instanceFieldsForCopy(type.internalName, roots) ?: emptyList()
    val m = AsmMethod(ReflectApiNames.COPY, OBJECT_TYPE, arrayOf(ownerType))
    val ga = GeneratorAdapter(Opcodes.ACC_PUBLIC + Opcodes.ACC_STATIC, m, null, null, cw)
    ga.visitCode()
    if (!TypeIntrospection.hasPublicNoArgConstructor(type.internalName, roots)) {
      ga.throwException(
        Type.getType(UnsupportedOperationException::class.java),
        "No public no-arg constructor for ${type.internalName.replace('/', '.')}",
      )
      ga.endMethod()
      return
    }
    ga.newInstance(ownerType)
    ga.dup()
    ga.invokeConstructor(ownerType, Method.getMethod("void <init> ()"))
    val destSlot = ga.newLocal(ownerType)
    ga.storeLocal(destSlot)
    for (ref in refs) {
      val decl = Type.getObjectType(ref.declaringInternal)
      val ft = Type.getType(ref.descriptor)
      ga.loadLocal(destSlot)
      ga.loadArg(0)
      ga.getField(decl, ref.name, ft)
      ga.putField(decl, ref.name, ft)
    }
    ga.loadLocal(destSlot)
    ga.returnValue()
    ga.endMethod()
  }

  private fun emitFields(type: TypeIntrospection.IntrospectedType, cw: ClassWriter, ownerType: Type) {
    val m = AsmMethod(ReflectApiNames.FIELDS, STRING_ARRAY_TYPE, arrayOf(ownerType))
    val ga = GeneratorAdapter(Opcodes.ACC_PUBLIC + Opcodes.ACC_STATIC, m, null, null, cw)
    ga.visitCode()
    val names = LinkedHashSet<String>()
    type.instanceFieldsMeta.keys.forEach { names.add(it) }
    type.properties.forEach { names.add(it.name) }

    val nameList = names.toList()
    ga.push(nameList.size)
    ga.newArray(STRING_TYPE)
    for (i in nameList.indices) {
      ga.dup()
      ga.push(i)
      ga.push(nameList[i])
      ga.arrayStore(STRING_TYPE)
    }
    ga.returnValue()
    ga.endMethod()
  }

  private fun forEachPropertyNameOrder(type: TypeIntrospection.IntrospectedType): List<String> {
    val ordered = ArrayList<String>()
    val seen = HashSet<String>()
    for (p in type.properties) {
      if (!ReflectPropertyAnalysis.beanReadable(p, type)) {
        continue
      }
      if (seen.add(p.name)) {
        ordered.add(p.name)
      }
    }
    for ((name, _) in type.fields) {
      if (seen.add(name)) {
        ordered.add(name)
      }
    }
    return ordered
  }

  private fun emitForEachField(type: TypeIntrospection.IntrospectedType, cw: ClassWriter, ownerType: Type) {
    val m = AsmMethod(ReflectApiNames.FOR_EACH_FIELD, Type.VOID_TYPE, arrayOf(ownerType, BICONSUMER_TYPE))
    val ga = GeneratorAdapter(Opcodes.ACC_PUBLIC + Opcodes.ACC_STATIC, m, null, null, cw)
    ga.visitCode()
    ga.loadArg(1)
    val nonNullConsumer = ga.newLabel()
    ga.ifNonNull(nonNullConsumer)
    ga.throwException(Type.getType(NullPointerException::class.java), "consumer")
    ga.mark(nonNullConsumer)
    for ((name, desc) in type.fields) {
      ga.loadArg(1)
      ga.push(name)
      ga.loadArg(0)
      val ft = Type.getType(desc)
      ga.getField(ownerType, name, ft)
      ga.box(ft)
      ga.invokeInterface(BICONSUMER_TYPE, M_BICONS_ACCEPT)
    }
    ga.returnValue()
    ga.endMethod()
  }

  private fun emitForEachProperty(type: TypeIntrospection.IntrospectedType, cw: ClassWriter, ownerType: Type) {
    val m = AsmMethod(ReflectApiNames.FOR_EACH_PROPERTY, Type.VOID_TYPE, arrayOf(ownerType, BICONSUMER_TYPE))
    val ga = GeneratorAdapter(Opcodes.ACC_PUBLIC + Opcodes.ACC_STATIC, m, null, null, cw)
    ga.visitCode()
    ga.loadArg(1)
    val nonNullConsumer = ga.newLabel()
    ga.ifNonNull(nonNullConsumer)
    ga.throwException(Type.getType(NullPointerException::class.java), "consumer")
    ga.mark(nonNullConsumer)
    for (name in forEachPropertyNameOrder(type)) {
      ga.loadArg(1)
      ga.push(name)
      ga.loadArg(0)
      val pbean = type.properties.firstOrNull { it.name == name && ReflectPropertyAnalysis.beanReadable(it, type) }
      if (pbean != null) {
        if (pbean.getterName != null && pbean.getterDesc != null) {
          val rt = Type.getReturnType(pbean.getterDesc)
          ga.invokeVirtual(ownerType, AsmMethod(pbean.getterName, pbean.getterDesc))
          ga.box(rt)
        } else if (pbean.fieldName != null && type.fields.containsKey(pbean.fieldName)) {
          val fd = type.fields.getValue(pbean.fieldName)
          ga.getField(ownerType, pbean.fieldName, Type.getType(fd))
          ga.box(Type.getType(fd))
        } else {
          continue
        }
      } else {
        val desc = type.fields[name] ?: continue
        ga.getField(ownerType, name, Type.getType(desc))
        ga.box(Type.getType(desc))
      }
      ga.invokeInterface(BICONSUMER_TYPE, M_BICONS_ACCEPT)
    }
    ga.returnValue()
    ga.endMethod()
  }

  private fun emitForEachMethod(type: TypeIntrospection.IntrospectedType, cw: ClassWriter, methodBindings: List<MethodIdBinding>) {
    val m = AsmMethod(ReflectApiNames.FOR_EACH_METHOD, Type.VOID_TYPE, arrayOf(BICONSUMER_TYPE))
    val ga = GeneratorAdapter(Opcodes.ACC_PUBLIC + Opcodes.ACC_STATIC, m, null, null, cw)
    ga.visitCode()
    ga.loadArg(0)
    val nonNullConsumer = ga.newLabel()
    ga.ifNonNull(nonNullConsumer)
    ga.throwException(Type.getType(NullPointerException::class.java), "consumer")
    ga.mark(nonNullConsumer)
    val bindings =
      methodBindings
        .filter { it.userClassInternal == type.internalName }
        .sortedWith(compareBy({ it.name }, { it.descriptor }))
    for (b in bindings) {
      ga.loadArg(0)
      ga.push(b.name)
      ga.newInstance(METHOD_ID_TYPE)
      ga.dup()
      ga.push(b.id)
      ga.invokeConstructor(METHOD_ID_TYPE, M_REFLECT_METHOD_ID_INIT)
      ga.invokeInterface(BICONSUMER_TYPE, M_BICONS_ACCEPT)
    }
    ga.returnValue()
    ga.endMethod()
  }

  /** String compare on arg1 (name) then runs [thenBlock] when equal. Builds if/eq chains. */
  private fun stringEqualsThen(ga: GeneratorAdapter, literal: String, thenBlock: () -> Unit) {
    ga.loadArg(1)
    ga.push(literal)
    ga.invokeVirtual(STRING_TYPE, AsmMethod("equals", Type.BOOLEAN_TYPE, arrayOf(OBJECT_TYPE)))
    val next = ga.newLabel()
    ga.ifZCmp(GeneratorAdapter.EQ, next)
    thenBlock()
    ga.mark(next)
  }

  private fun verifyNonNull(m: Method, cw: ClassWriter) : GeneratorAdapter {
    val ga = GeneratorAdapter(Opcodes.ACC_PUBLIC + Opcodes.ACC_STATIC, m, null, null, cw)
    ga.visitCode()
    ga.loadArg(1)
    val nonNull = ga.newLabel()
    ga.ifNonNull(nonNull)
    ga.throwException(Type.getType(NullPointerException::class.java), "name")
    ga.mark(nonNull)
    return ga
  }
}
