package me.stringdotjar.reflectaot.codegen

import java.io.File

/**
 * Java source emitter for the bootstrap class used when output mode is Java-only or when Java bootstrap is required.
 *
 * This mirrors the behavior of [BootstrapBytecodeEmitter] but writes `ReflectAOTBootstrap.java` so environments that
 * compile generated sources instead of loading generated bytecode can still install [me.stringdotjar.reflectaot.ReflectAOTServices].
 */
object JavaBootstrapEmitter {

  /**
   * Writes `ReflectAOTBootstrap.java` under `me/stringdotjar/reflectaot/generated` beneath [outputDir].
   *
 * The generated static block installs the generated `ReflectAOTRegistry` class and `ReflectAOTMethodIdTable` through
 * the public APIs on `ReflectAOTServices` in the runtime module.
   *
   * @param outputDir Root directory that will receive the generated Java source tree.
   */
  fun emit(outputDir: File) {
    outputDir.mkdirs()
    val pkg = File(outputDir, "me/stringdotjar/reflectaot/generated")
    pkg.mkdirs()
    val f = File(pkg, "ReflectAOTBootstrap.java")
    f.writeText(
      """
      package me.stringdotjar.reflectaot.generated;

      import me.stringdotjar.reflectaot.ReflectAOTServices;

      public final class ReflectAOTBootstrap {

          static {
              ReflectAOTServices.install(new ReflectAOTRegistry());
              ReflectAOTServices.installMethodIds(new ReflectAOTMethodIdTable());
          }

          private ReflectAOTBootstrap() {
          }
      }
      """.trimIndent() + "\n",
    )
  }
}
