package me.stringdotjar.reflectaot.codegen

import java.io.File
import org.objectweb.asm.Type

/**
 * Java source emitter for the `ReflectAOTMethodIdTable` class that backs `Reflect.method` resolution at runtime.
 *
 * The emitted type implements `ReflectAOTMethodIdResolver` from the runtime module and mirrors the dispatch shape of
 * [MethodIdTableBytecodeEmitter] for projects that compile generated Java instead of loading generated bytecode.
 */
object MethodIdTableJavaEmitter {

  /**
   * Writes `ReflectAOTMethodIdTable.java` under the generated package rooted at [javaOut].
   *
   * @param javaOut Root directory that will receive the `me/stringdotjar/reflectaot/generated` tree.
   * @param bindings Stable bindings produced by [ReflectAOTCodegen] after overload resolution.
   */
  fun emit(javaOut: File, bindings: List<MethodIdBinding>) {
    val pkg = "me.stringdotjar.reflectaot.generated"
    val dir = File(javaOut, pkg.replace('.', '/'))
    dir.mkdirs()
    val sb = StringBuilder()
    sb.append("package ").append(pkg).append(";\n\n")
    sb.append("import me.stringdotjar.reflectaot.ReflectAOTMethodIdResolver;\n")
    sb.append("import me.stringdotjar.reflectaot.ReflectMethodId;\n\n")
    sb.append("public final class ReflectAOTMethodIdTable implements ReflectAOTMethodIdResolver {\n\n")
    val sorted = bindings.sortedBy { it.id }
    for (b in sorted) {
      sb.append("  private static final ReflectMethodId M").append(b.id).append(" = new ReflectMethodId(").append(b.id).append(");\n")
    }
    sb.append("\n  public ReflectAOTMethodIdTable() {}\n\n")
    sb.append("  public ReflectMethodId resolve(Class<?> clazz, String name, String descriptor) {\n")
    if (sorted.isEmpty()) {
      sb.append("    throw new IllegalArgumentException(\"")
      sb.append(MethodIdTableMessages.escapeJavaStringLiteralContent(MethodIdTableMessages.noReflectMethodCallSites()))
      sb.append("\");\n")
    } else {
      for (b in sorted) {
        val fq = internalToClassLiteralSource(b.userClassInternal)
        sb.append("    if (clazz == ").append(fq)
        sb.append(" && \"").append(escape(b.name)).append("\".equals(name)")
        sb.append(" && \"").append(escape(b.descriptor)).append("\".equals(descriptor)) {\n")
        sb.append("      return M").append(b.id).append(";\n")
        sb.append("    }\n")
      }
      sb.append("    throw new IllegalArgumentException(\"")
      sb.append(MethodIdTableMessages.escapeJavaStringLiteralContent(MethodIdTableMessages.unknownReflectMethodTriple()))
      sb.append("\");\n")
    }
    sb.append("  }\n\n")
    sb.append("  public ReflectMethodId resolve(Class<?> clazz, String name) {\n")
    if (sorted.isEmpty()) {
      sb.append("    throw new IllegalArgumentException(\"")
      sb.append(MethodIdTableMessages.escapeJavaStringLiteralContent(MethodIdTableMessages.noReflectMethodCallSites()))
      sb.append("\");\n")
    } else {
      sb.append("    int matches = 0;\n")
      sb.append("    ReflectMethodId found = null;\n")
      for (b in sorted) {
        val fq = internalToClassLiteralSource(b.userClassInternal)
        sb.append("    if (clazz == ").append(fq).append(" && \"").append(escape(b.name)).append("\".equals(name)) {\n")
        sb.append("      if (matches != 0) {\n")
        sb.append("        throw new IllegalArgumentException(\"")
        sb.append(MethodIdTableMessages.escapeJavaStringLiteralContent(MethodIdTableMessages.ambiguousReflectMethodClassAndName()))
        sb.append("\");\n")
        sb.append("      }\n")
        sb.append("      matches = 1;\n")
        sb.append("      found = M").append(b.id).append(";\n")
        sb.append("    }\n")
      }
      sb.append("    if (matches == 0) {\n")
      sb.append("      throw new IllegalArgumentException(\"")
      sb.append(MethodIdTableMessages.escapeJavaStringLiteralContent(MethodIdTableMessages.unknownReflectMethodClassAndName()))
      sb.append("\");\n")
      sb.append("    }\n")
      sb.append("    return found;\n")
    }
    sb.append("  }\n}\n")
    File(dir, "ReflectAOTMethodIdTable.java").writeText(sb.toString())
  }

  /**
   * Escapes a Java string literal fragment for safe embedding inside double quotes in generated sources.
   *
   * @param s Raw string content from a method name or descriptor.
   * @return The escaped string safe to embed between double quotes in generated Java.
   */
  private fun escape(s: String): String = s.replace("\\", "\\\\").replace("\"", "\\\"")

  /**
   * Renders a `SomeType.class` or `int.class` style literal used in generated Java comparisons against `Class` parameters.
   *
   * @param internal JVM internal name for a class or array type as stored on [MethodIdBinding.userClassInternal].
   * @return Java source text ending with `.class` suitable for comparisons in emitted resolver methods.
   * @throws IllegalStateException When [internal] uses an array or reference encoding this helper does not support.
   */
  private fun internalToClassLiteralSource(internal: String): String {
    if (internal.startsWith("[")) {
      var s = internal
      var dims = 0
      while (s.startsWith("[")) {
        dims++
        s = s.substring(1)
      }
      val base =
        when (s) {
          "I" -> "int"
          "Z" -> "boolean"
          "B" -> "byte"
          "S" -> "short"
          "C" -> "char"
          "J" -> "long"
          "F" -> "float"
          "D" -> "double"
          "V" -> "void"
          else ->
            if (s.startsWith("L") && s.endsWith(";")) {
              s.substring(1, s.length - 1).replace('/', '.')
            } else {
              throw IllegalStateException("Unsupported type in descriptor: " + internal)
            }
        }
      return base + "[]".repeat(dims) + ".class"
    }
    if (internal.startsWith("L") && internal.endsWith(";")) {
      return internal.substring(1, internal.length - 1).replace('/', '.') + ".class"
    }
    // MethodIdBinding.userClassInternal uses ASM internal names with slashes, not L...; class descriptors.
    return Type.getObjectType(internal).className + ".class"
  }
}
