package me.stringdotjar.reflectaot.codegen

/**
 * Selects which artifacts [ReflectAOTCodegen] writes. Configured from the Gradle extension.
 *
 * @property CLASS Emit `.class` files only (typical JVM / Android / transpiler inputs).
 * @property JAVA Emit `.java` mirrors for environments that cannot load generated bytecode early.
 * @property BOTH Emit both; Java bootstrap is skipped when bytecode already installs services.
 */
enum class ReflectAOTOutput {

  CLASS,

  JAVA,

  BOTH
}
