package me.stringdotjar.reflectaot.codegen

/**
 * Selects which artifacts [ReflectAOTCodegen] writes. Values are configured from the Gradle `reflectaot` extension.
 */
enum class ReflectAOTOutput {

  /**
   * Emit `.class` files only. This is the default for normal JVM builds and bytecode-first transpilers.
   */
  CLASS,

  /**
   * Emit `.java` sources only. Useful when a downstream toolchain cannot consume generated bytecode directly.
   */
  JAVA,

  /**
   * Emit bytecode and Java mirrors from the same model. Java bootstrap emission is skipped when bytecode already
   * installs services, so initialization stays single-sourced.
   */
  BOTH
}
