package me.stringdotjar.reflectaot;

import java.util.List;

/**
 * Hand-written {@link ReflectAOTRuntime} behaviors that do not require per-type generated
 * accessors.
 *
 * <p>These helpers are called from generated {@code ReflectAOTRegistry} implementations so
 * generated bytecode stays small. This class must not use {@link java.lang.reflect} types.
 */
public final class ReflectAOTDefaultDispatch {

  private ReflectAOTDefaultDispatch() {}

  /**
   * @param a first value
   * @param b second value
   * @return negative, zero, or positive ordering
   */
  public static int compare(Object a, Object b) {
    if (a == b) {
      return 0;
    }
    if (a == null) {
      return -1;
    }
    if (b == null) {
      return 1;
    }
    if (a instanceof String && b instanceof String) {
      return ((String) a).compareTo((String) b);
    }
    if (a instanceof Comparable<?> && a.getClass() == b.getClass()) {
      @SuppressWarnings("unchecked")
      Comparable<Object> ca = (Comparable<Object>) a;
      return ca.compareTo(b);
    }
    if (a instanceof Number && b instanceof Number) {
      return Double.compare(((Number) a).doubleValue(), ((Number) b).doubleValue());
    }
    throw new IllegalArgumentException(
        "Reflect.compare: unsupported types "
            + a.getClass().getName()
            + " vs "
            + b.getClass().getName());
  }

  /**
   * @param f1 first token
   * @param f2 second token
   * @return {@code true} when the two tokens are identical (reference equality)
   */
  public static boolean compareMethods(Object f1, Object f2) {
    return f1 == f2;
  }

  /**
   * @param v value to test
   * @return {@code true} for {@link Runnable} or {@link java.util.concurrent.Callable}
   */
  public static boolean isFunction(Object v) {
    return v instanceof Runnable || v instanceof java.util.concurrent.Callable<?>;
  }

  /**
   * @param v value to test
   * @return {@code true} for non-null non-primitive-like values (Haxe-style object classification)
   */
  public static boolean isObject(Object v) {
    return v != null
        && !(v instanceof Boolean
            || v instanceof Number
            || v instanceof Character
            || v instanceof String);
  }

  /**
   * @param v value to test
   * @return {@code true} when {@code v} is a Java {@code enum} constant
   */
  public static boolean isEnumValue(Object v) {
    return v != null && v.getClass().isEnum();
  }

  /**
   * @param f opaque token
   * @return varargs wrapper (not implemented in v1)
   */
  public static Object makeVarArgs(Object f) {
    throw new UnsupportedOperationException("makeVarArgs not specialized");
  }

  /**
   * @param o target object
   * @param name field name
   * @param args call arguments
   * @return invocation result
   */
  public static Object callMethod(Object o, Object name, List<?> args) {
    throw new UnsupportedOperationException("callMethod not specialized for " + safe(o));
  }

  /**
   * @param o target object
   * @return shallow copy (not implemented generically without generated support)
   */
  public static Object copy(Object o) {
    throw new UnsupportedOperationException("copy not specialized for " + safe(o));
  }

  /**
   * @param o target object
   * @param name field name
   * @return {@code false} (JVM anonymous structures are not modeled here)
   */
  public static boolean deleteField(Object o, String name) {
    return false;
  }

  private static String safe(Object o) {
    return o == null ? "null" : o.getClass().getName();
  }
}
